-- Thanos complete database schema
-- Run this as one query in the NEW Thanos Supabase project.
-- WARNING: This script deletes and recreates the Thanos application tables.
-- Do not run it in a project containing data you need to keep.

begin;

-- Remove application objects from earlier attempts so this script is self-contained.
drop view if exists qualifying_leads cascade;
drop table if exists enrichment_jobs cascade;
drop table if exists lead_matches cascade;
drop table if exists companies cascade;
drop table if exists raw_events cascade;
drop table if exists schema_migrations cascade;

create table schema_migrations (
    version text primary key,
    applied_at timestamptz not null default now()
);

create table raw_events (
    id bigint generated by default as identity primary key,
    event_type text,
    company_number text,
    payload jsonb not null,
    received_at timestamptz not null default now()
);

create table companies (
    company_number text primary key,
    company_name text not null,
    date_of_creation date,
    sic_codes jsonb not null default '[]'::jsonb,
    registered_office_address jsonb not null default '{}'::jsonb,
    company_status text,
    raw_data jsonb not null default '{}'::jsonb,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    enrichment_status text not null default 'pending',
    enriched_at timestamptz,
    is_lead boolean not null default false,
    lead_status text not null default 'not_matching',
    matched_buzzwords jsonb not null default '[]'::jsonb,
    matched_sic_codes jsonb not null default '[]'::jsonb,
    incorporated_today boolean not null default false,
    last_screened_at timestamptz
);

create table lead_matches (
    id bigint generated by default as identity primary key,
    company_number text not null references companies(company_number) on delete cascade,
    match_type text not null,
    matched_value text not null,
    evidence jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique(company_number, match_type, matched_value)
);

create table enrichment_jobs (
    id bigint generated by default as identity primary key,
    company_number text not null references companies(company_number) on delete cascade,
    enrichment_scope text not null,
    status text not null default 'pending',
    attempts integer not null default 0,
    last_error text,
    created_at timestamptz not null default now(),
    started_at timestamptz,
    completed_at timestamptz
);

create unique index enrichment_jobs_initial_company_idx
    on enrichment_jobs(company_number)
    where enrichment_scope = 'initial_rest';

create index companies_lead_idx
    on companies(is_lead, incorporated_today, first_seen_at desc);

create index companies_date_of_creation_idx
    on companies(date_of_creation);

create index companies_enrichment_status_idx
    on companies(enrichment_status);

create index raw_events_company_number_idx
    on raw_events(company_number);

create view qualifying_leads as
select
    c.company_number,
    c.company_name,
    c.date_of_creation,
    c.sic_codes,
    c.registered_office_address,
    c.company_status,
    c.enrichment_status,
    c.lead_status,
    c.matched_buzzwords,
    c.matched_sic_codes,
    c.incorporated_today,
    c.first_seen_at,
    c.last_seen_at
from companies c
where c.is_lead = true
  and c.incorporated_today = true;

insert into schema_migrations(version)
values ('001_thanos_complete_schema');

commit;

-- Verification queries. These are read-only.
select
    table_name,
    table_type
from information_schema.tables
where table_schema = 'public'
  and table_name in (
      'schema_migrations',
      'raw_events',
      'companies',
      'lead_matches',
      'enrichment_jobs'
  )
order by table_name;

select
    table_name,
    column_name,
    data_type
from information_schema.columns
where table_schema = 'public'
  and table_name = 'companies'
order by ordinal_position;

select
    table_name,
    table_type
from information_schema.tables
where table_schema = 'public'
  and table_name = 'qualifying_leads';
